server:
  host: "0.0.0.0"
  port: 8075
  timezone: Asia/Taipei

db:
  dialect: "mysql"
  user: "root"
  password: "123456"
  host: "0.0.0.0"
  port: 3307
  dbname: "block"
  flag: "charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci"
  interval: 60
  maxconn: 2

redis:
  host: "172.40.0.4"
  port: 6379
  database: 0
  auth: "AeLP6RFYQJdzayTRLrWZ64NxbTh7yhNt"
  max_idle: 80
  max_active: 12000
  idle_timeout: 2500


http:
  header:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Headers: "Content-Type, Authorization"
    Access-Control-Allow-Methods: "GET, POST, OPTIONS, HEAD, PATCH, DELETE"
