server:
  host: "0.0.0.0"
  port: 8080
  timezone: Asia/Taipei
  rpcUrl: "https://data-seed-prebsc-2-s3.binance.org:8545/"
  IndexerNumber: 10

db:
  dialect: "mysql"
  user: "root"
  password: "123456"
  host: "0.0.0.0"
  port: 3307
  dbname: "rf"
  flag: "charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci"
  interval: 60
  maxconn: 2


http:
  header:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Headers: "Content-Type, Authorization"
    Access-Control-Allow-Methods: "GET, POST, OPTIONS, HEAD, PATCH, DELETE"
